server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/demoDB
    driver-class-name: org.postgresql.Driver
    username: usr
    password: pwd
  flyway:
    enabled: true
